services:
  mandados-app:
    build: .
    container_name: mandados_app
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=5058
      - PLAN_GRATIS_LAUNCH=1
    ports:
      - "127.0.0.1:5058:5058"
    volumes:
      - ./mandados.db:/app/mandados.db
