services:
  caponera-app:
    build: .
    container_name: caponera_app
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=5054
    ports:
      - "127.0.0.1:5054:5054"
    volumes:
      - ./caponera.db:/app/caponera.db
